import type { SectionFinalSummaryResponse, PairFinalResultRow } from "@/lib/api/scoring";

// ── Excel export ──────────────────────────────────────────────────────────────
export async function exportResultsToExcel(
  summary: SectionFinalSummaryResponse,
  sectionName: string,
  competitionName: string
) {
  const { default: writeXlsxFile } = await import("write-excel-file/browser");

  const danceKeys = Object.keys(summary.rankings[0]?.perDance ?? {});
  const headers = [
    { value: "Place", fontWeight: "bold" as const },
    { value: "Start #", fontWeight: "bold" as const },
    { value: "Total sum", fontWeight: "bold" as const },
    { value: "Tie resolution", fontWeight: "bold" as const },
    ...danceKeys.map((d) => ({ value: `Dance: ${d}`, fontWeight: "bold" as const })),
  ];
  const dataRows = summary.rankings.map((row: PairFinalResultRow) => [
    { value: row.finalPlacement, type: Number },
    { value: row.startNumber, type: Number },
    { value: row.totalSum, type: Number },
    { value: row.tieResolution !== "NONE" ? row.tieResolution : "" },
    ...danceKeys.map((d) => ({ value: row.perDance[d] ?? 0, type: Number })),
  ]);

  await writeXlsxFile([headers, ...dataRows], {
    fileName: `${competitionName}_${sectionName}_results.xlsx`,
    sheet: sectionName.slice(0, 31),
  });
}

// ── PDF export via browser print ──────────────────────────────────────────────
export function exportResultsToPDF(
  summary: SectionFinalSummaryResponse,
  sectionName: string,
  competitionName: string
) {
  const rows = summary.rankings
    .map(
      (r: PairFinalResultRow) =>
        `<tr>
          <td>${r.finalPlacement}</td>
          <td>${r.startNumber}</td>
          <td>${r.totalSum}</td>
          <td>${Object.entries(r.perDance).map(([d, p]) => `${d}:${p}`).join(", ")}</td>
          <td>${r.tieResolution !== "NONE" ? r.tieResolution : ""}</td>
        </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${competitionName} — ${sectionName} Results</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 12px; }
  h1 { font-size: 16px; margin-bottom: 4px; }
  h2 { font-size: 13px; color: #666; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
  th { background: #f5f5f5; font-weight: bold; }
  tr:nth-child(even) { background: #fafafa; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<h1>${competitionName}</h1>
<h2>${sectionName} — Final Results</h2>
<table>
  <thead>
    <tr>
      <th>Place</th><th>Start #</th><th>Sum</th><th>Per dance</th><th>Note</th>
    </tr>
  </thead>
  <tbody>${rows}</tbody>
</table>
<p style="margin-top:20px;font-size:10px;color:#999">
  Generated by DanceApp · ${new Date().toLocaleString("sk-SK")}
</p>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}
